import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import VideoPlayer from "@/components/VideoPlayer";
import SideIsland from "@/components/SideIsland";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Header />
      </nav>
      <main>
        <div className="flex relative flex-col items-center justify-center min-h-[var(--content-height)] py-2">
          <div className="absolute top-[24px] left-[26px]">
            <SideIsland />
          </div>
          <VideoPlayer />
        </div>
      </main>
    </>
  );
}
